# ---- GENERAL ----

profile=high-quality
priority=high
vo=dmabuf-wayland
cursor-autohide=1000

# ---- SUBTITLE ----

sub-font="SF Pro Rounded"
sub-ass-override=force
sub-font-size=48
sub-border-size=1
sub-color="#FFFFFFFF"
sub-border-color="#FF262626"
sub-shadow-color="#33000000"
sub-shadow-offset=1

# ---- Video Output & Scaling ----
# ---- Color management ----

target-prim=auto
target-trc=auto
vf=format=colorlevels=full:colormatrix=auto
video-output-levels=full

# ---- Dithering ----

dither-depth=auto
temporal-dither=yes
dither=fruit

# ---- Debanding (ideal for anime) ----
deband=yes
deband-iterations=4
deband-threshold=30
deband-range=16
deband-grain=5
